# Generated by Django 2.2 on 2019-04-02 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('location', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('category', models.CharField(choices=[('fire', 'Fire'), ('earth', 'Earth'), ('water', 'Water'), ('storm', 'Storm'), ('disease', 'Disease'), ('industrial', 'Industrial')], default='fire', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('description', models.TextField()),
                ('added_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Person')),
            ],
        ),
    ]
