# Generated by Django 2.2 on 2019-04-02 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('unknown', 'Unknown'), ('missing', 'Missing'), ('found', 'Found'), ('safe', 'Safe'), ('injured', 'Injured'), ('deceased', 'Deceased'), ('unaffected', 'Unaffected')], default='unknown', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.PersonStatus'),
        ),
    ]
