# Generated by Django 2.2 on 2019-04-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20190402_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personstatus',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
